import type { TimelineItemData } from "./types";

export const timelineData: TimelineItemData[] = [
  {
    year: "Nov 2025 - Present",
    title: "Siargao Trading Road",
    company: "",
    companyType: "Marketplace",
    isHackathon: true,
    description: "B2B marketplace connecting suppliers and stores in Siargao with role-based access, order management, and location tracking.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
      "https://img.shields.io/badge/React%20Native-61DAFB?style=for-the-badge&logo=react&logoColor=black",
      "https://img.shields.io/badge/Flutter-02569B?style=for-the-badge&logo=flutter&logoColor=white",
      "https://img.shields.io/badge/Framer_Motion-EF008F?style=for-the-badge&logo=framer&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Go-00ADD8?style=for-the-badge&logo=go&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/Vercel-000000?style=for-the-badge&logo=vercel&logoColor=white",
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
    ],
  },
  {
    year: "Nov - Dec 2025",
    title: "Seery",
    company: "Seedify Hackathon",
    companyType: "Fintech",
    isHackathon: true,
    description: "Decentralized crypto prediction platform on BNB Chain with AI-powered forecasts and Chainlink/Pyth oracles.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
      "https://img.shields.io/badge/MUI-007FFF?style=for-the-badge&logo=mui&logoColor=white",
      "https://img.shields.io/badge/Framer_Motion-EF008F?style=for-the-badge&logo=framer&logoColor=white",
      "https://img.shields.io/badge/wagmi-6366f1?style=for-the-badge&logo=ethereum&logoColor=white",
      "https://img.shields.io/badge/viem-6366f1?style=for-the-badge&logo=ethereum&logoColor=white",
      "https://img.shields.io/badge/MetaMask-FF7139?style=for-the-badge&logo=metamask&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Express.js-000000?style=for-the-badge&logo=express&logoColor=white",
      "https://img.shields.io/badge/BNB_Chain-F3BA2F?style=for-the-badge&logo=binance&logoColor=black",
      "https://img.shields.io/badge/Solidity-363636?style=for-the-badge&logo=solidity&logoColor=white",
      "https://img.shields.io/badge/ethers.js-3C3C3D?style=for-the-badge&logo=ethereum&logoColor=white",
      "https://img.shields.io/badge/Hardhat-FFF100?style=for-the-badge&logo=hardhat&logoColor=black",
    ],
    devops: [
      "https://img.shields.io/badge/Vercel-000000?style=for-the-badge&logo=vercel&logoColor=white",
      "https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/OpenAI-74aa9c?style=for-the-badge&logo=openai&logoColor=white",
      "https://img.shields.io/badge/Testnet-FF6B6B?style=for-the-badge&logo=ethereum&logoColor=white",
      "https://img.shields.io/badge/Mainnet-4CAF50?style=for-the-badge&logo=ethereum&logoColor=white",
    ],
  },
  {
    year: "Jul - Oct 2025",
    title: "SplitSafe",
    company: "WCHL Hackathon - Winner",
    companyType: "Fintech, LegalTech",
    isHackathon: true,
    description: "Trustless escrow platform on Internet Computer with native Bitcoin support. Winner of DoraHacks WCHL25 National and Regional Rounds.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
      "https://img.shields.io/badge/Redux-764ABC?style=for-the-badge&logo=redux&logoColor=white",
      "https://img.shields.io/badge/TailwindCSS-06B6D4?style=for-the-badge&logo=tailwindcss&logoColor=white",
      "https://img.shields.io/badge/Framer_Motion-EF008F?style=for-the-badge&logo=framer&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/ICP-000000?style=for-the-badge&logo=internet-computer&logoColor=white",
      "https://img.shields.io/badge/bitcoin-2F3134?style=for-the-badge&logo=bitcoin&logoColor=white",
      "https://img.shields.io/badge/SEI-000000?style=for-the-badge&logoColor=white",
      "https://img.shields.io/badge/Motoko-3B00B9?style=for-the-badge&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHZpZXdCb3g9IjAgMCAyNCAyNCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHBhdGggZD0iTTEyIDJMMiA3VjE3TDEyIDIyTDIyIDE3VjdMMTIgMloiIHN0cm9rZT0id2hpdGUiIHN0cm9rZS13aWR0aD0iMiIgZmlsbD0ibm9uZSIvPgo8cGF0aCBkPSJNMTIgMkwxMiAyMkwyMiAxN1Y3TDEyIDJaIiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPHBhdGggZD0iTTIgN0wxMiAxMkwyMiA3IiBzdHJva2U9IndoaXRlIiBzdHJva2Utd2lkdGg9IjIiIGZpbGw9Im5vbmUiLz4KPC9zdmc+",
      "https://img.shields.io/badge/Story_Protocol-FF6B6B?style=for-the-badge",
      "https://img.shields.io/badge/Constellation-4A90E2?style=for-the-badge",
    ],
    devops: [
      "https://img.shields.io/badge/Terraform-7B42BC?style=for-the-badge&logo=terraform&logoColor=white",
      "https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white",
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/OpenAI-74aa9c?style=for-the-badge&logo=openai&logoColor=white",
      "https://img.shields.io/badge/Resend-FF6B6B?style=for-the-badge&logo=mailgun&logoColor=white",
      "https://img.shields.io/badge/Pusher-300D4F?style=for-the-badge&logo=pusher&logoColor=white",
      "https://img.shields.io/badge/Sentry-362D59?style=for-the-badge&logo=sentry&logoColor=white",
      "https://img.shields.io/badge/Grafana-F46800?style=for-the-badge&logo=grafana&logoColor=white",
      "https://img.shields.io/badge/Loki-2C5EE8?style=for-the-badge&logo=loki&logoColor=white",
    ],
  },
  {
    year: "Oct 2022 - June 2025",
    title: "Senior Software Engineer",
    company: "Urbanstems",
    companyUrl: "https://urbanstems.com/",
    companyType: "E-commerce",
    description: "Fixed bugs, implemented features, integrated UPS, Easypost, Netsuite, and Shopify Plus APIs. Tech support during peak seasons.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=node.js&logoColor=white",
      "https://img.shields.io/badge/Prisma-2D3748?style=for-the-badge&logo=prisma&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/MongoDB-47A248?style=for-the-badge&logo=mongodb&logoColor=white",
      "https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/AWS_Lambda-FF9900?style=for-the-badge&logo=aws-lambda&logoColor=white",
      "https://img.shields.io/badge/Terraform-7B42BC?style=for-the-badge&logo=terraform&logoColor=white",
      "https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white",
    ],
    unitTest: [
      "https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/Shopify-96BF48?style=for-the-badge&logo=shopify&logoColor=white",
      "https://img.shields.io/badge/Netsuite-FF6C37?style=for-the-badge&logo=oracle&logoColor=white",
    ],
  },
  {
    year: "Aug 2022 - Jan 2025",
    title: "Senior Software Engineer",
    company: "Ancileo Pte. Ltd.",
    companyUrl: "https://ancileo.com/",
    companyType: "InsurTech",
    description: "Tech support, bug fixes, implemented first unit tests, whitelabels for Policy products, and AI Pricing Configuration App with AWS Bedrock and Claude v3.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Laravel-FF2D20?style=for-the-badge&logo=laravel&logoColor=white",
      "https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=node.js&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/Redis-DC382D?style=for-the-badge&logo=redis&logoColor=white",
      "https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white",
    ],
    unitTest: [
      "https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/AWS_Bedrock-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/Claude-FF6B35?style=for-the-badge&logo=anthropic&logoColor=white",
    ],
  },
  {
    year: "Jan - May 2023",
    title: "Frontend Engineer",
    company: "Chronicled",
    companyType: "HealthTech",
    description: "Integrated Reactflow.js for supply chain automation solutions in pharmaceuticals and healthcare industries.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
      "https://img.shields.io/badge/MUI-007FFF?style=for-the-badge&logo=mui&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white",
    ],
    unitTest: [
      "https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white",
      "https://img.shields.io/badge/Unit_Testing-25A162?style=for-the-badge&logo=test&logoColor=white",
      "https://img.shields.io/badge/TDD-25A162?style=for-the-badge&logo=test&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/Reactflow-FF6B6B?style=for-the-badge&logo=react&logoColor=white",
    ],
  },
  {
    year: "Oct 2021 - Oct 2022",
    title: "Cloud Engineer",
    company: "Cebu Pacific Air, Inc.",
    companyUrl: "https://www.cebupacificair.com/en-PH/",
    companyType: "TravelTech",
    description: "Implemented web application for internal automation, setup Jenkins CI/CD, migrated projects from VMware Tanzu to AWS EKS.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white",
      "https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Go-00ADD8?style=for-the-badge&logo=go&logoColor=white",
      "https://img.shields.io/badge/Gin-00ADD8?style=for-the-badge&logo=go&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/MongoDB-47A248?style=for-the-badge&logo=mongodb&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/Kubernetes-326CE5?style=for-the-badge&logo=kubernetes&logoColor=white",
      "https://img.shields.io/badge/Jenkins-D24939?style=for-the-badge&logo=jenkins&logoColor=white",
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/AWS_EKS-FF9900?style=for-the-badge&logo=amazon-eks&logoColor=white",
      "https://img.shields.io/badge/AWS_CloudFormation-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/Terraform-7B42BC?style=for-the-badge&logo=terraform&logoColor=white",
      "https://img.shields.io/badge/GitHub_Actions-2088FF?style=for-the-badge&logo=github-actions&logoColor=white",
      "https://img.shields.io/badge/VMware_Tanzu-607078?style=for-the-badge&logo=vmware&logoColor=white",
      "https://img.shields.io/badge/Azure-0078D4?style=for-the-badge&logo=azure-devops&logoColor=white",
      "https://img.shields.io/badge/Harbor-60B932?style=for-the-badge&logo=harbor&logoColor=white",
    ],
  },
  {
    year: "Nov 2017 - Oct 2021",
    title: "Fullstack Developer",
    company: "Valhalla Online Services, Inc.",
    companyType: "RandomTech",
    description: "Fullstack developer implementing complex features, API integrations, and overseeing projects including Cryptocoin Token and 12rnd Training Camp.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB",
      "https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white",
      "https://img.shields.io/badge/Redux-764ABC?style=for-the-badge&logo=redux&logoColor=white",
      "https://img.shields.io/badge/MUI-007FFF?style=for-the-badge&logo=mui&logoColor=white",
      "https://img.shields.io/badge/Vue.js-4FC08D?style=for-the-badge&logo=vue.js&logoColor=white",
      "https://img.shields.io/badge/Web3.js-F16822?style=for-the-badge&logo=web3.js&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Express.js-000000?style=for-the-badge&logo=express&logoColor=white",
      "https://img.shields.io/badge/Solidity-363636?style=for-the-badge&logo=solidity&logoColor=white",
      "https://img.shields.io/badge/Truffle-3A2E22?style=for-the-badge&logo=truffle&logoColor=white",
      "https://img.shields.io/badge/Laravel-FF2D20?style=for-the-badge&logo=laravel&logoColor=white",
      "https://img.shields.io/badge/Serverless-FD5750?style=for-the-badge&logo=serverless&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/MongoDB-47A248?style=for-the-badge&logo=mongodb&logoColor=white",
      "https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white",
      "https://img.shields.io/badge/DynamoDB-4053D6?style=for-the-badge&logo=amazon-dynamodb&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/Docker-2496ED?style=for-the-badge&logo=docker&logoColor=white",
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/AWS_EC2-FF9900?style=for-the-badge&logo=amazon-ec2&logoColor=white",
      "https://img.shields.io/badge/AWS_Lambda-FF9900?style=for-the-badge&logo=awslambda&logoColor=white",
      "https://img.shields.io/badge/AWS_S3-569A31?style=for-the-badge&logo=amazon-s3&logoColor=white",
      "https://img.shields.io/badge/AWS_SNS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
      "https://img.shields.io/badge/AWS_SES-FF9900?style=for-the-badge&logo=amazon-ses&logoColor=white",
      "https://img.shields.io/badge/AWS_SQS-FF9900?style=for-the-badge&logo=amazon-sqs&logoColor=white",
      "https://img.shields.io/badge/AWS_ECR-FF9900?style=for-the-badge&logo=amazon-ecr&logoColor=white",
      "https://img.shields.io/badge/Jenkins-D24939?style=for-the-badge&logo=jenkins&logoColor=white",
      "https://img.shields.io/badge/Webpack-8DD6F9?style=for-the-badge&logo=webpack&logoColor=black",
      "https://img.shields.io/badge/Gulp-CF4647?style=for-the-badge&logo=gulp&logoColor=white",
    ],
    unitTest: [
      "https://img.shields.io/badge/Cypress-17202C?style=for-the-badge&logo=cypress&logoColor=white",
      "https://img.shields.io/badge/Newman-FF6C37?style=for-the-badge&logo=postman&logoColor=white",
    ],
    misc: [
      "https://img.shields.io/badge/Storybook-FF4785?style=for-the-badge&logo=storybook&logoColor=white",
      "https://img.shields.io/badge/React_Hooks-61DAFB?style=for-the-badge&logo=react&logoColor=black",
      "https://img.shields.io/badge/Context_API-61DAFB?style=for-the-badge&logo=react&logoColor=black",
    ],
  },
  {
    year: "Aug 2014 - Aug 2017",
    title: "Fullstack Developer",
    company: "Philwebservices, Inc.",
    companyType: "Fintech",
    description: "Team lead for 1FX Pay project, integrated 20+ APIs, handled frontend/backend, deployments, and client communication.",
    type: "work",
    fe: [
      "https://img.shields.io/badge/Vue.js-4FC08D?style=for-the-badge&logo=vue.js&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/Laravel-FF2D20?style=for-the-badge&logo=laravel&logoColor=white",
    ],
    databases: [
      "https://img.shields.io/badge/MySQL-4479A1?style=for-the-badge&logo=mysql&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/AWS-FF9900?style=for-the-badge&logo=amazon-aws&logoColor=white",
    ],
  },
  {
    year: "2010 - 2014",
    title: "Bachelor's in Computer Science",
    company: "University of San Carlos",
    companyUrl: "https://usc.edu.ph/",
    companyType: "Education",
    description: "Graduated with focus on web technologies and software engineering. Created GLUM Sys thesis project.",
    type: "education",
    fe: [
      "https://img.shields.io/badge/jQuery-0769AD?style=for-the-badge&logo=jquery&logoColor=white",
      "https://img.shields.io/badge/JavaScript-F7DF1E?style=for-the-badge&logo=javascript&logoColor=black",
      "https://img.shields.io/badge/Bootstrap-7952B3?style=for-the-badge&logo=bootstrap&logoColor=white",
    ],
    be: [
      "https://img.shields.io/badge/PHP-777BB4?style=for-the-badge&logo=php&logoColor=white",
    ],
    devops: [
      "https://img.shields.io/badge/FileZilla-BF0000?style=for-the-badge&logo=filezilla&logoColor=white",
      "https://img.shields.io/badge/cPanel-FF6C2C?style=for-the-badge&logo=cpanel&logoColor=white",
    ],
  },
];
